// Copies this example into deploy/docker-compose.yml as inline `configs:` entries, so the
// CE stack seeds it on `docker compose up -d` (services examples-seed and customer-request-stub)
// and `docker compose run --rm examples <command>` drives it (service examples).
// Run it after changing setup.mjs, cli.mjs, a flow, the agent, a payload or the stub.
//
//   node scripts/sync-deploy.mjs           rewrite the generated block
//   node scripts/sync-deploy.mjs --check   exit 1 if the compose file is out of date
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const compose = join(root, '../../deploy/docker-compose.yml');
const BEGIN = '  # >>> customer-request example (generated by examples/customer-request/scripts/sync-deploy.mjs, do not edit)';
const END = '  # <<< customer-request example';

const FILES = [
  ['example-customer-request-setup', 'scripts/setup.mjs'],
  ['example-customer-request-intake', 'flows/intake.json'],
  ['example-customer-request-reply-router', 'flows/reply-router.json'],
  ['example-customer-request-agent', 'agents/request-classifier.json'],
  ['example-customer-request-stub', 'stub/server.js'],
  ['example-customer-request-cli', 'scripts/cli.mjs'],
  ['example-customer-request-payload-request', 'payloads/request.json'],
  ['example-customer-request-payload-reply', 'payloads/reply.json'],
];

function entry(name, file) {
  const text = readFileSync(join(root, file), 'utf8').replace(/\r\n/g, '\n').replace(/\n+$/, '');
  if (/^\s/.test(text)) throw new Error(`${file}: first line must not start with whitespace (YAML block scalar)`);
  // compose interpolates `content`, so every literal `$` is written as `$$`.
  const body = text
    .split('\n')
    .map((l) => (l ? `      ${l.replaceAll('$', '$$$$')}` : ''))
    .join('\n');
  return `  # ${file}\n  ${name}:\n    content: |\n${body}`;
}

const block = [BEGIN, ...FILES.map(([n, f]) => entry(n, f)), END].join('\n\n');

const raw = readFileSync(compose, 'utf8');
const eol = raw.includes('\r\n') ? '\r\n' : '\n';
const current = raw.replace(/\r\n/g, '\n');
const start = current.indexOf(BEGIN);
const stop = current.indexOf(END);
let next;
if (start >= 0 && stop > start) {
  next = current.slice(0, start) + block + current.slice(stop + END.length);
} else {
  // First run: append to the end of the top-level `configs:` section.
  const at = current.indexOf('\nvolumes:\n');
  if (at < 0) throw new Error('no top-level "volumes:" section in deploy/docker-compose.yml');
  next = current.slice(0, at) + '\n' + block + '\n' + current.slice(at);
}

if (process.argv.includes('--check')) {
  if (next !== current) {
    console.error('deploy/docker-compose.yml is out of date: run "node examples/customer-request/scripts/sync-deploy.mjs"');
    process.exit(1);
  }
  console.log('deploy/docker-compose.yml is up to date');
} else {
  writeFileSync(compose, next.replace(/\n/g, eol));
  console.log(next === current ? 'deploy/docker-compose.yml already up to date' : 'updated deploy/docker-compose.yml');
}
